name: Static code analysis

on: [pull_request]

jobs:
#  static-code-analysis:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: PHP_CodeSniffer
#        uses: docker://jakzal/phpqa:php7.4-alpine
#        with:
#          args: phpcs
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: phpcs
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
