name: Static code analysis

on: [pull_request]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHP_CodeSniffer
        uses: docker://jakzal/phpqa:php7.4-alpine
        with:
          args: phpcs
